# Generated by Django 2.1.7 on 2019-02-14 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_framework_expiring_authtoken', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiringToken',
        ),
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expire_auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
